title: "JH's Blog"
email: karuseo01@gmail.com
timezone: UTC
baseurl:
permalink: "/:title/"
logo: 
favicon: 
author: Jh
paginate: 30
disqus: #댓글 다는 기능
locale: ko-kr
lang: ko-kr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
    name: Kim ji-hoon
    display_name: poppop001
    avatar:
    email: karuseo01@gmail.com
    web: 
    twitter: 
    description: 

# Social
social:
  instagram: 
  facebook: 
  twitter: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
